### ISSUE TITLE
Wrong command-line flag for tile size tau.

### ISSUE THREAD

**Issue by mstrout** [CompOpt4Apps/DiamondTilingViz#1]
dhmn217:DiamondTilingViz mstrout$ ./slice-viz -N 40 -T 4 -s 2 -e 4 -g halfradius -t 12
CmdParams_parseParams: spatialDim = 40
CmdParams_parseParams: numTimeSteps = 4
CmdParams_parseParams: Tstart = 2
CmdParams_parseParams: Tend = 4
CmdParams_parseParams: grid_spacing_approach = halfradius
CmdParams_parseParams: tiling = 12
Error: -t 12 is not in list of possible strings

t is already being used for the kind of tiling.  Instead need to use -a for tau.

**Comment by aMiss-aWry** [comment]
Fixed so tau uses -a in latest pull request.

**Comment by mstrout** [comment]
This is fixed.
